// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bakimonarim.dataaccess.Concrete;

#nullable disable

namespace bakimonarim.dataaccess.Migrations
{
    [DbContext(typeof(BakimOnarimDbContext))]
    partial class BakimOnarimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("bakimonarim.entity.Varlik", b =>
                {
                    b.Property<int>("VarlikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VarlikID"), 1L, 1);

                    b.Property<string>("BuskiNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuzenleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("GrupID")
                        .HasColumnType("int");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KM")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastikEbat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastikSayi")
                        .HasColumnType("int");

                    b.Property<string>("MotorNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Saat")
                        .HasColumnType("int");

                    b.Property<string>("SaseNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sube")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarlikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarlikKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("VarlikID");

                    b.ToTable("TBL_Varlik");
                });

            modelBuilder.Entity("bakimonarim.entity.VGrup", b =>
                {
                    b.Property<int>("GrupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupID"), 1L, 1);

                    b.Property<int>("AracSinifID")
                        .HasColumnType("int");

                    b.Property<string>("GrupMarka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrupModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastikTip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrupID");

                    b.ToTable("TBL_VGrup");
                });
#pragma warning restore 612, 618
        }
    }
}
